version: "2"
services: 
  node:
    build:
      context: .
      dockerfile: ./container/node.Dockerfile
    ports:
      - 3000:3000
  web_server:
    build:
      context: .
      dockerfile: ./container/webserver.Dockerfile
    ports:
      - 80:80
      - 443:443
    links:
      - node
    volumes:
    - ./caddy/.caddy:/root/.caddy
    - ./caddy/Caddyfile:/etc/Caddyfile
  mysql: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
